version: '3'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /node_modules
      - /src
    ports:
      - 3000:3000
    links:
      - db
  db:
    image: mongo
    restart: on-failure
    expose:
      - 27017
    volumes:
      - /data/db
